# This file configures the analyzer, which statically analyzes Dart code.
# It checks for errors, warnings, and lints, helping you maintain good coding practices.

# Activate a set of recommended lints for Flutter apps, packages, and plugins.
include: package:flutter_lints/flutter.yaml

linter:
  # Customize the lint rules for your project below.
  rules:
    # Uncomment the lines below to modify default lints:
    # avoid_print: false          # Disable the 'avoid_print' rule
    # prefer_single_quotes: true # Enforce single quotes instead of double quotes

# Additional info:
# The analyzer can be run from the command line with:
# flutter analyze
# More lints and documentation: https://dart.dev/lints
