// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5T8g2QEwihPEVBg_bvk73sY6XVlgIagA',
    appId: '1:1041878879585:web:c87a659260e48e71e10920',
    messagingSenderId: '1041878879585',
    projectId: 'careercompass-993db',
    authDomain: 'careercompass-993db.firebaseapp.com',
    storageBucket: 'careercompass-993db.firebasestorage.app',
    measurementId: 'G-3G0KXB3MG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWgDsXURJzwBZYOSsviqII2NJxbQ5gj6o',
    appId: '1:1041878879585:android:688724f88ef17df3e10920',
    messagingSenderId: '1041878879585',
    projectId: 'careercompass-993db',
    storageBucket: 'careercompass-993db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMZ4zlruyKn7_CQ18ZglwigJz-gx4F954',
    appId: '1:1041878879585:ios:05de0574bd3cccebe10920',
    messagingSenderId: '1041878879585',
    projectId: 'careercompass-993db',
    storageBucket: 'careercompass-993db.firebasestorage.app',
    iosBundleId: 'com.example.careercompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMZ4zlruyKn7_CQ18ZglwigJz-gx4F954',
    appId: '1:1041878879585:ios:05de0574bd3cccebe10920',
    messagingSenderId: '1041878879585',
    projectId: 'careercompass-993db',
    storageBucket: 'careercompass-993db.firebasestorage.app',
    iosBundleId: 'com.example.careercompass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5T8g2QEwihPEVBg_bvk73sY6XVlgIagA',
    appId: '1:1041878879585:web:09ff476f05e71bace10920',
    messagingSenderId: '1041878879585',
    projectId: 'careercompass-993db',
    authDomain: 'careercompass-993db.firebaseapp.com',
    storageBucket: 'careercompass-993db.firebasestorage.app',
    measurementId: 'G-W1FBPWEV3Z',
  );
}
